export const OBTER_PROJETOS = "OBTER_PROJETOS"
export const OBTER_TAREFAS = "OBTER_TAREFAS"
export const CADASTRA_PROJETOS = "CADASTRA_PROJETOS"
export const EDITAR_PROJETOS = "EDITAR_PROJETOS "
export const EXCLUIR_PROJETOS = "EXCLUIR_PROJETOS"
export const CADASTRA_TAREFAS = "CADASTRA_TAREFAS"
export const EDITAR_TAREFA = "EDITAR_TAREFA "

