export const OBTER_PROJETOS = "OBTER_PROJETOS"
export const CADASTRA_PROJETOS = "CADASTRA_PROJETOS"
export const EDITAR_PROJETOS = "EDITAR_PROJETOS "
export const EXCLUIR_PROJETOS = "EXCLUIR_PROJETOS"
